/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as UnauthenticatedResetPasswordIndexRouteImport } from './routes/_unauthenticated/reset-password/index'
import { Route as UnauthenticatedLoginIndexRouteImport } from './routes/_unauthenticated/login/index'
import { Route as UnauthenticatedActivateIndexRouteImport } from './routes/_unauthenticated/activate/index'
import { Route as AuthenticatedPresetsIndexRouteImport } from './routes/_authenticated/presets/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAnalyzeIndexRouteImport } from './routes/_authenticated/analyze/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedDashboardDynamicsRouteImport } from './routes/_authenticated/dashboard/dynamics'
import { Route as AuthenticatedDashboardArchiveRouteImport } from './routes/_authenticated/dashboard/archive'
import { Route as AuthenticatedDashboardReportSnapshotIdRouteImport } from './routes/_authenticated/dashboard/report/$snapshotId'

const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const UnauthenticatedResetPasswordIndexRoute =
  UnauthenticatedResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => UnauthenticatedRouteRoute,
  } as any)
const UnauthenticatedLoginIndexRoute =
  UnauthenticatedLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => UnauthenticatedRouteRoute,
  } as any)
const UnauthenticatedActivateIndexRoute =
  UnauthenticatedActivateIndexRouteImport.update({
    id: '/activate/',
    path: '/activate/',
    getParentRoute: () => UnauthenticatedRouteRoute,
  } as any)
const AuthenticatedPresetsIndexRoute =
  AuthenticatedPresetsIndexRouteImport.update({
    id: '/presets/',
    path: '/presets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyzeIndexRoute =
  AuthenticatedAnalyzeIndexRouteImport.update({
    id: '/analyze/',
    path: '/analyze/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardDynamicsRoute =
  AuthenticatedDashboardDynamicsRouteImport.update({
    id: '/dashboard/dynamics',
    path: '/dashboard/dynamics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardArchiveRoute =
  AuthenticatedDashboardArchiveRouteImport.update({
    id: '/dashboard/archive',
    path: '/dashboard/archive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReportSnapshotIdRoute =
  AuthenticatedDashboardReportSnapshotIdRouteImport.update({
    id: '/dashboard/report/$snapshotId',
    path: '/dashboard/report/$snapshotId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard/archive': typeof AuthenticatedDashboardArchiveRoute
  '/dashboard/dynamics': typeof AuthenticatedDashboardDynamicsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/analyze/': typeof AuthenticatedAnalyzeIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/presets/': typeof AuthenticatedPresetsIndexRoute
  '/activate/': typeof UnauthenticatedActivateIndexRoute
  '/login/': typeof UnauthenticatedLoginIndexRoute
  '/reset-password/': typeof UnauthenticatedResetPasswordIndexRoute
  '/dashboard/report/$snapshotId': typeof AuthenticatedDashboardReportSnapshotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard/archive': typeof AuthenticatedDashboardArchiveRoute
  '/dashboard/dynamics': typeof AuthenticatedDashboardDynamicsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/analyze': typeof AuthenticatedAnalyzeIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/presets': typeof AuthenticatedPresetsIndexRoute
  '/activate': typeof UnauthenticatedActivateIndexRoute
  '/login': typeof UnauthenticatedLoginIndexRoute
  '/reset-password': typeof UnauthenticatedResetPasswordIndexRoute
  '/dashboard/report/$snapshotId': typeof AuthenticatedDashboardReportSnapshotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/dashboard/archive': typeof AuthenticatedDashboardArchiveRoute
  '/_authenticated/dashboard/dynamics': typeof AuthenticatedDashboardDynamicsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/analyze/': typeof AuthenticatedAnalyzeIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/presets/': typeof AuthenticatedPresetsIndexRoute
  '/_unauthenticated/activate/': typeof UnauthenticatedActivateIndexRoute
  '/_unauthenticated/login/': typeof UnauthenticatedLoginIndexRoute
  '/_unauthenticated/reset-password/': typeof UnauthenticatedResetPasswordIndexRoute
  '/_authenticated/dashboard/report/$snapshotId': typeof AuthenticatedDashboardReportSnapshotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/archive'
    | '/dashboard/dynamics'
    | '/admin/'
    | '/analyze/'
    | '/dashboard/'
    | '/presets/'
    | '/activate/'
    | '/login/'
    | '/reset-password/'
    | '/dashboard/report/$snapshotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/archive'
    | '/dashboard/dynamics'
    | '/admin'
    | '/analyze'
    | '/dashboard'
    | '/presets'
    | '/activate'
    | '/login'
    | '/reset-password'
    | '/dashboard/report/$snapshotId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_unauthenticated'
    | '/_public/'
    | '/_authenticated/dashboard/archive'
    | '/_authenticated/dashboard/dynamics'
    | '/_authenticated/admin/'
    | '/_authenticated/analyze/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/presets/'
    | '/_unauthenticated/activate/'
    | '/_unauthenticated/login/'
    | '/_unauthenticated/reset-password/'
    | '/_authenticated/dashboard/report/$snapshotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_unauthenticated/reset-password/': {
      id: '/_unauthenticated/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof UnauthenticatedResetPasswordIndexRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_unauthenticated/login/': {
      id: '/_unauthenticated/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof UnauthenticatedLoginIndexRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_unauthenticated/activate/': {
      id: '/_unauthenticated/activate/'
      path: '/activate'
      fullPath: '/activate/'
      preLoaderRoute: typeof UnauthenticatedActivateIndexRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_authenticated/presets/': {
      id: '/_authenticated/presets/'
      path: '/presets'
      fullPath: '/presets/'
      preLoaderRoute: typeof AuthenticatedPresetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyze/': {
      id: '/_authenticated/analyze/'
      path: '/analyze'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AuthenticatedAnalyzeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/dynamics': {
      id: '/_authenticated/dashboard/dynamics'
      path: '/dashboard/dynamics'
      fullPath: '/dashboard/dynamics'
      preLoaderRoute: typeof AuthenticatedDashboardDynamicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/archive': {
      id: '/_authenticated/dashboard/archive'
      path: '/dashboard/archive'
      fullPath: '/dashboard/archive'
      preLoaderRoute: typeof AuthenticatedDashboardArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/report/$snapshotId': {
      id: '/_authenticated/dashboard/report/$snapshotId'
      path: '/dashboard/report/$snapshotId'
      fullPath: '/dashboard/report/$snapshotId'
      preLoaderRoute: typeof AuthenticatedDashboardReportSnapshotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardArchiveRoute: typeof AuthenticatedDashboardArchiveRoute
  AuthenticatedDashboardDynamicsRoute: typeof AuthenticatedDashboardDynamicsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAnalyzeIndexRoute: typeof AuthenticatedAnalyzeIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedPresetsIndexRoute: typeof AuthenticatedPresetsIndexRoute
  AuthenticatedDashboardReportSnapshotIdRoute: typeof AuthenticatedDashboardReportSnapshotIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardArchiveRoute: AuthenticatedDashboardArchiveRoute,
  AuthenticatedDashboardDynamicsRoute: AuthenticatedDashboardDynamicsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAnalyzeIndexRoute: AuthenticatedAnalyzeIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedPresetsIndexRoute: AuthenticatedPresetsIndexRoute,
  AuthenticatedDashboardReportSnapshotIdRoute:
    AuthenticatedDashboardReportSnapshotIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedActivateIndexRoute: typeof UnauthenticatedActivateIndexRoute
  UnauthenticatedLoginIndexRoute: typeof UnauthenticatedLoginIndexRoute
  UnauthenticatedResetPasswordIndexRoute: typeof UnauthenticatedResetPasswordIndexRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedActivateIndexRoute: UnauthenticatedActivateIndexRoute,
  UnauthenticatedLoginIndexRoute: UnauthenticatedLoginIndexRoute,
  UnauthenticatedResetPasswordIndexRoute:
    UnauthenticatedResetPasswordIndexRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
